spring:
  application:
    name: spring-kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hello-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    topic: hello-topic

logging:
  level:
    com.soutelloit.springkafka: INFO
